// Generated by contracts/export-abi.sh. Do not edit by hand. Addresses: set after deployment or override via FACE_MATCH_REGISTRY_ADDRESS.
export const FACE_MATCH_REGISTRY_ABI = [
  {
    "type": "function",
    "name": "getRecord",
    "inputs": [
      {
        "name": "imageHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct FaceMatchRegistry.Record",
        "components": [
          {
            "name": "imageHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "faceHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "postUrl",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "timestamp",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "submitter",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "record",
    "inputs": [
      {
        "name": "imageHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "faceHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "postUrl",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "records",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "imageHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "faceHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "postUrl",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "timestamp",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "submitter",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "MatchRecorded",
    "inputs": [
      {
        "name": "imageHash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "faceHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "postUrl",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "timestamp",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "EmptyUrl",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroHash",
    "inputs": []
  }
] as const;

export const CONTRACT_ADDRESSES: Record<number, `0x${string}` | undefined> = {
  421614: undefined, // Arbitrum Sepolia
  42161: undefined, // Arbitrum One
};
