#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

forge build

ARTIFACT="out/FaceMatchRegistry.sol/FaceMatchRegistry.json"
OUT_FILE="$SCRIPT_DIR/../apps/web/lib/contract.ts"

# Preserve existing address values, if any, before we overwrite the file.
ADDR_421614="undefined"
ADDR_42161="undefined"
ADDR_11155111="undefined"
if [ -f "$OUT_FILE" ]; then
  existing=$(grep -oE '421614: [^,]+,' "$OUT_FILE" || true)
  if [ -n "$existing" ]; then
    ADDR_421614=$(echo "$existing" | sed -E 's/421614: ([^,]+),/\1/')
  fi
  existing=$(grep -oE '42161: [^,]+,' "$OUT_FILE" || true)
  if [ -n "$existing" ]; then
    ADDR_42161=$(echo "$existing" | sed -E 's/42161: ([^,]+),/\1/')
  fi
  existing=$(grep -oE '11155111: [^,]+,' "$OUT_FILE" || true)
  if [ -n "$existing" ]; then
    ADDR_11155111=$(echo "$existing" | sed -E 's/11155111: ([^,]+),/\1/')
  fi
fi

if command -v jq >/dev/null 2>&1; then
  ABI_JSON=$(jq '.abi' "$ARTIFACT")
else
  ABI_JSON=$(node -e "console.log(JSON.stringify(require('./$ARTIFACT').abi, null, 2))")
fi

mkdir -p "$(dirname "$OUT_FILE")"

{
  echo "// Generated by contracts/export-abi.sh. Do not edit by hand. Addresses: set after deployment or override via FACE_MATCH_REGISTRY_ADDRESS."
  echo "export const FACE_MATCH_REGISTRY_ABI = $ABI_JSON as const;"
  echo ""
  echo "export const CONTRACT_ADDRESSES: Record<number, \`0x\${string}\` | undefined> = {"
  echo "  421614: $ADDR_421614, // Arbitrum Sepolia"
  echo "  42161: $ADDR_42161, // Arbitrum One"
  echo "  11155111: $ADDR_11155111, // Ethereum Sepolia"
  echo "};"
} > "$OUT_FILE"

echo "Wrote ABI to $OUT_FILE"
